### ISSUE TITLE
missing date-fns requiring undocumented dependency

### ISSUE THREAD

**Issue by amadden80** [SllyQ/bs-date-fns#1]
I needed to add date-fns to my dependencies for this package to work.  

Is this expected?

Should add this requirement to docs?  
`npm install date-fns --save`

**Comment by nielmond** [comment]
I found this to be the case as well. Shouldn't it be made as a dependency of this module so we don't have it add it ourselves?

**Comment by nielmond** [comment]
Oh, it actually is a dependency https://github.com/SllyQ/bs-date-fns/blob/master/package.json

Maybe try making it a regular dependency rather than a peerDependency?

FWIW, I used yarn and ran into the same issue as @amadden80 who appears to have used npm.

**Comment by SllyQ** [comment]
Moved date-fns from peerDependencies to dependencies
