### ISSUE TITLE
Remove deprecated jsx v2

### ISSUE THREAD

**Issue by eWert-Online** [SllyQ/bs-date-fns#12]
Since version 8 of Bucklescript, jsx v2 has been removed.
(https://github.com/BuckleScript/bucklescript/commit/ef7e8a928b5885edebe874469030aeb0a885c6fe)

Projects with Bucklescript version >8 do not compile with `bs-date-fns` as a dependency.

**Comment by SllyQ** [comment]
Fixed, thanks for PR
