### ISSUE TITLE
Native bindings

### ISSUE THREAD

**Issue by kossnocorp** [SllyQ/bs-date-fns#4]
Hey! One of the date-fns authors is here 😄 

We're interested in supporting Bucklescript bindings natively in date-fns, and I'm wondering if you can help with that.

We generate TypeScript and Flow typings from JSDoc definitions, and I'm sure it's possible to do the same with BS, but the problem is that we know nothing about the language and the ecosystem.

Native bindings will help keep them always up-to-date, make it dependency free for the users and also introduce the support for locales.

Here the examples of the typings generation:

- https://github.com/date-fns/date-fns/blob/HEAD/scripts/build/_lib/typings/typeScript.js
- https://github.com/date-fns/date-fns/blob/HEAD/scripts/build/_lib/typings/flow.js

What do you think?

**Comment by SllyQ** [comment]
That sounds like a good idea.

Will take a look on the weekend. Ping me if I don't reply before next week :)

**Comment by kossnocorp** [comment]
@SllyQ awesome, I will try to not forget about it as well 😉!

**Comment by SllyQ** [comment]
@kossnocorp I looked into the typings and played around with the code generation. Looks doable, managed to get a very basic version of bindings generated (with half the features removed). I think the best way forward would be for me to do to some more work on it next week and then I can open an WIP PR in date-fns repo and we can then move further discussion there.
