### ISSUE TITLE
Consider "unflipping" the methods

### ISSUE THREAD

**Issue by baldurh** [SllyQ/bs-date-fns#6]
Currently some methods are "flipped"

>  to work better with currying and make better use of pipe operator

```reason
laterDate |> DateFns.isAfter(earlierDate) /* true */
DateFns.isAfter(earlierDate, laterDate) /* true */
```

This is (on purpose) the opposite of how the original JS version works:

```JavaScript
// isAfter Description:
// Is the first date after the second one?

// Is 10 July 1989 after 11 February 1987?
var result = isAfter(new Date(1989, 6, 10), new Date(1987, 1, 11))
// isAfter(laterDate, earlierDate)
//=> true
```

The reason documentation, and it’s creators now recommends the [Pipe first](https://reasonml.github.io/docs/en/pipe-first) operator (`->`) (formerly known as fast pipe) and seems to be moving away from the "pizza" operator (`|>`). See also [this issue](https://github.com/reasonml/reasonml.github.io/issues/435)

That means people will want to be using these methods with `->` which mean code like this will be more common:

```reason
laterDate -> DateFns.isAfter(earlierDate) // (DateFns.isAfter(laterDate, earlierDate))
```

which currently would (confusingly) resolve to `false`.

Also, now you have more control over where the piped parameter lands in the method execution

```reason
// In this example I assume the binding has the same signature as the original method
laterDate -> DateFns.isAfter(earlierDate) /* true */
laterDate -> DateFns.isAfter(earlierDate, _) /* false */
```

It is obviously really confusing to use the official date-fns documentation along with this binding currently.

Would you consider releasing a major version with breaking changes where the methods have the same signature is the same as in the original library?

**Comment by SllyQ** [comment]
The new version with unflipped methods and 2.x bindings is in npm prerelease `@next`
